{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e5ffbcea-53b1-4935-bef3-07f6559c6ae1",
   "metadata": {},
   "outputs": [],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import torch\n",
    "\n",
    "print(\"numpy:\", np.__version__)\n",
    "print(\"pandas:\", pd.__version__)\n",
    "print(\"torch:\", torch.__version__)\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "import os\n",
    "import math\n",
    "import random\n",
    "from datetime import datetime\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "from sklearn.metrics import (\n",
    "    mean_squared_error, mean_absolute_error, r2_score,\n",
    "    accuracy_score, precision_score, recall_score, f1_score, roc_auc_score\n",
    ")\n",
    "from sklearn.linear_model import Ridge, LogisticRegression\n",
    "from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier\n",
    "\n",
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "\n",
    "import yfinance as yf\n",
    "import ta\n",
    "\n",
    "SEED = 42\n",
    "np.random.seed(SEED)\n",
    "random.seed(SEED)\n",
    "torch.manual_seed(SEED)\n",
    "\n",
    "DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "print(\"Using device:\", DEVICE)\n",
    "tickers = [\n",
    "    \"SPY\", \"QQQ\", \"IWM\",\n",
    "    \"XLK\", \"XLF\", \"XLV\", \"XLE\", \"XLI\", \"XLP\", \"XLU\", \"XLY\", \"XLB\", \"XLRE\",\n",
    "    \"AAPL\", \"MSFT\", \"NVDA\", \"AMZN\", \"GOOGL\", \"META\", \"JPM\", \"XOM\", \"JNJ\", \"UNH\", \"PG\"\n",
    "]\n",
    "\n",
    "start_date = \"2012-01-01\"\n",
    "end_date = \"2026-01-01\"\n",
    "\n",
    "len(tickers)\n",
    "raw = yf.download(\n",
    "    tickers,\n",
    "    start=start_date,\n",
    "    end=end_date,\n",
    "    auto_adjust=True,\n",
    "    progress=False,\n",
    "    group_by=\"ticker\"\n",
    ")\n",
    "\n",
    "print(raw.shape)\n",
    "raw.tail()\n",
    "frames = []\n",
    "\n",
    "for ticker in tickers:\n",
    "    df_t = raw[ticker].copy()\n",
    "    df_t.columns = [c.lower().replace(\" \", \"_\") for c in df_t.columns]\n",
    "    df_t = df_t.reset_index()\n",
    "    df_t[\"ticker\"] = ticker\n",
    "    frames.append(df_t)\n",
    "\n",
    "panel = pd.concat(frames, ignore_index=True)\n",
    "panel = panel.rename(columns={\"date\": \"Date\"})\n",
    "panel = panel.sort_values([\"ticker\", \"Date\"]).reset_index(drop=True)\n",
    "\n",
    "print(panel.shape)\n",
    "panel.head()\n",
    "def add_basic_features(df):\n",
    "    df = df.copy()\n",
    "    df = df.sort_values([\"ticker\", \"Date\"])\n",
    "    \n",
    "    df[\"log_close\"] = np.log(df[\"close\"])\n",
    "    df[\"ret_1\"] = df.groupby(\"ticker\")[\"log_close\"].diff()\n",
    "    df[\"simple_ret_1\"] = df.groupby(\"ticker\")[\"close\"].pct_change()\n",
    "    \n",
    "    for w in [5, 10, 20, 60]:\n",
    "        df[f\"ret_mean_{w}\"] = (\n",
    "            df.groupby(\"ticker\")[\"ret_1\"]\n",
    "            .rolling(w).mean()\n",
    "            .reset_index(level=0, drop=True)\n",
    "        )\n",
    "        df[f\"ret_std_{w}\"] = (\n",
    "            df.groupby(\"ticker\")[\"ret_1\"]\n",
    "            .rolling(w).std()\n",
    "            .reset_index(level=0, drop=True)\n",
    "        )\n",
    "        df[f\"mom_{w}\"] = df.groupby(\"ticker\")[\"close\"].pct_change(w)\n",
    "    \n",
    "    df[\"hl_range\"] = (df[\"high\"] - df[\"low\"]) / df[\"close\"]\n",
    "    df[\"oc_return\"] = (df[\"close\"] - df[\"open\"]) / df[\"open\"]\n",
    "    \n",
    "    df[\"log_volume\"] = np.log1p(df[\"volume\"])\n",
    "    df[\"vol_chg_1\"] = df.groupby(\"ticker\")[\"log_volume\"].diff()\n",
    "    df[\"vol_mean_20\"] = (\n",
    "        df.groupby(\"ticker\")[\"log_volume\"]\n",
    "        .rolling(20).mean()\n",
    "        .reset_index(level=0, drop=True)\n",
    "    )\n",
    "    \n",
    "    return df\n",
    "\n",
    "panel = add_basic_features(panel)\n",
    "panel.head()\n",
    "def add_technical_indicators(df):\n",
    "    out = []\n",
    "    \n",
    "    for ticker, g in df.groupby(\"ticker\"):\n",
    "        g = g.sort_values(\"Date\").copy()\n",
    "        \n",
    "        g[\"rsi_14\"] = ta.momentum.RSIIndicator(close=g[\"close\"], window=14).rsi()\n",
    "        \n",
    "        macd_obj = ta.trend.MACD(close=g[\"close\"])\n",
    "        g[\"macd\"] = macd_obj.macd()\n",
    "        g[\"macd_signal\"] = macd_obj.macd_signal()\n",
    "        g[\"macd_diff\"] = macd_obj.macd_diff()\n",
    "        \n",
    "        bb_obj = ta.volatility.BollingerBands(close=g[\"close\"], window=20, window_dev=2)\n",
    "        g[\"bb_width\"] = bb_obj.bollinger_wband()\n",
    "        \n",
    "        atr_obj = ta.volatility.AverageTrueRange(\n",
    "            high=g[\"high\"], low=g[\"low\"], close=g[\"close\"], window=14\n",
    "        )\n",
    "        g[\"atr_14\"] = atr_obj.average_true_range()\n",
    "        \n",
    "        out.append(g)\n",
    "    \n",
    "    return pd.concat(out, ignore_index=True)\n",
    "\n",
    "panel = add_technical_indicators(panel)\n",
    "panel.head()\n",
    "# --- Market context features: clean single-level columns first ---\n",
    "\n",
    "# 1) Download VIX cleanly\n",
    "vix_raw = yf.download(\n",
    "    \"^VIX\",\n",
    "    start=start_date,\n",
    "    end=end_date,\n",
    "    auto_adjust=True,\n",
    "    progress=False\n",
    ")\n",
    "\n",
    "# If yfinance returns multi-index columns, flatten them\n",
    "if isinstance(vix_raw.columns, pd.MultiIndex):\n",
    "    vix_raw.columns = [col[0] if isinstance(col, tuple) else col for col in vix_raw.columns]\n",
    "\n",
    "vix = vix_raw.reset_index()[[\"Date\", \"Close\"]].copy()\n",
    "vix = vix.rename(columns={\"Close\": \"vix_close\"})\n",
    "vix[\"vix_ret_1\"] = np.log(vix[\"vix_close\"]).diff()\n",
    "\n",
    "# 2) Build SPY context from panel\n",
    "spy_context = panel.loc[panel[\"ticker\"] == \"SPY\", [\"Date\", \"ret_1\", \"ret_std_20\", \"mom_20\"]].copy()\n",
    "spy_context = spy_context.rename(columns={\n",
    "    \"ret_1\": \"spy_ret_1\",\n",
    "    \"ret_std_20\": \"spy_vol_20\",\n",
    "    \"mom_20\": \"spy_mom_20\"\n",
    "})\n",
    "\n",
    "# 3) Defensive column flattening, just in case\n",
    "if isinstance(panel.columns, pd.MultiIndex):\n",
    "    panel.columns = [col[0] if isinstance(col, tuple) else col for col in panel.columns]\n",
    "\n",
    "if isinstance(spy_context.columns, pd.MultiIndex):\n",
    "    spy_context.columns = [col[0] if isinstance(col, tuple) else col for col in spy_context.columns]\n",
    "\n",
    "if isinstance(vix.columns, pd.MultiIndex):\n",
    "    vix.columns = [col[0] if isinstance(col, tuple) else col for col in vix.columns]\n",
    "\n",
    "# 4) Merge\n",
    "panel = panel.merge(spy_context, on=\"Date\", how=\"left\")\n",
    "panel = panel.merge(vix, on=\"Date\", how=\"left\")\n",
    "\n",
    "print(panel.shape)\n",
    "panel.head()\n",
    "panel[\"day_of_week\"] = panel[\"Date\"].dt.dayofweek\n",
    "panel[\"month\"] = panel[\"Date\"].dt.month\n",
    "panel[\"quarter\"] = panel[\"Date\"].dt.quarter\n",
    "\n",
    "panel[\"dow_sin\"] = np.sin(2 * np.pi * panel[\"day_of_week\"] / 5)\n",
    "panel[\"dow_cos\"] = np.cos(2 * np.pi * panel[\"day_of_week\"] / 5)\n",
    "panel[\"month_sin\"] = np.sin(2 * np.pi * panel[\"month\"] / 12)\n",
    "panel[\"month_cos\"] = np.cos(2 * np.pi * panel[\"month\"] / 12)\n",
    "def create_targets(df, horizons=[1, 5, 21]):\n",
    "    df = df.copy()\n",
    "    df = df.sort_values([\"ticker\", \"Date\"])\n",
    "    \n",
    "    for h in horizons:\n",
    "        df[f\"future_ret_{h}\"] = (\n",
    "            df.groupby(\"ticker\")[\"ret_1\"]\n",
    "            .transform(lambda x: x.shift(-1).rolling(h).sum())\n",
    "        )\n",
    "        \n",
    "        df[f\"future_rv_{h}\"] = (\n",
    "            df.groupby(\"ticker\")[\"ret_1\"]\n",
    "            .transform(lambda x: np.sqrt((x.shift(-1) ** 2).rolling(h).sum()))\n",
    "        )\n",
    "        \n",
    "        def downside_semivol(x):\n",
    "            x = x.shift(-1)\n",
    "            x_neg_sq = np.minimum(x, 0) ** 2\n",
    "            return np.sqrt(pd.Series(x_neg_sq, index=x.index).rolling(h).sum())\n",
    "        \n",
    "        df[f\"future_dsv_{h}\"] = (\n",
    "            df.groupby(\"ticker\")[\"ret_1\"]\n",
    "            .transform(downside_semivol)\n",
    "        )\n",
    "        \n",
    "        df[f\"future_score_{h}\"] = df[f\"future_ret_{h}\"] / (df[f\"future_rv_{h}\"] + 1e-8)\n",
    "    \n",
    "    return df\n",
    "\n",
    "panel = create_targets(panel, horizons=[1, 5, 21])\n",
    "panel.head()\n",
    "for h in [1, 5, 21]:\n",
    "    median_vol_by_day = panel.groupby(\"Date\")[f\"future_rv_{h}\"].transform(\"median\")\n",
    "    panel[f\"quality_label_{h}\"] = (\n",
    "        (panel[f\"future_ret_{h}\"] > 0) &\n",
    "        (panel[f\"future_rv_{h}\"] < median_vol_by_day)\n",
    "    ).astype(int)\n",
    "\n",
    "panel[[f\"future_ret_5\", f\"future_rv_5\", f\"future_score_5\", f\"quality_label_5\"]].head(10)\n",
    "def add_technical_indicators(df):\n",
    "    out = []\n",
    "    \n",
    "    for ticker, g in df.groupby(\"ticker\"):\n",
    "        g = g.sort_values(\"Date\").copy()\n",
    "        \n",
    "        g[\"rsi_14\"] = ta.momentum.RSIIndicator(close=g[\"close\"], window=14).rsi()\n",
    "        \n",
    "        macd_obj = ta.trend.MACD(close=g[\"close\"])\n",
    "        g[\"macd\"] = macd_obj.macd()\n",
    "        g[\"macd_signal\"] = macd_obj.macd_signal()\n",
    "        g[\"macd_diff\"] = macd_obj.macd_diff()\n",
    "        \n",
    "        bb_obj = ta.volatility.BollingerBands(close=g[\"close\"], window=20, window_dev=2)\n",
    "        g[\"bb_width\"] = bb_obj.bollinger_wband()\n",
    "        \n",
    "        atr_obj = ta.volatility.AverageTrueRange(\n",
    "            high=g[\"high\"], low=g[\"low\"], close=g[\"close\"], window=14\n",
    "        )\n",
    "        g[\"atr_14\"] = atr_obj.average_true_range()\n",
    "        \n",
    "        out.append(g)\n",
    "    \n",
    "    return pd.concat(out, ignore_index=True)\n",
    "\n",
    "panel = add_technical_indicators(panel)\n",
    "print([c for c in panel.columns if c in [\"rsi_14\", \"macd\", \"macd_signal\", \"macd_diff\", \"bb_width\", \"atr_14\"]])\n",
    "spy_context = panel.loc[\n",
    "    panel[\"ticker\"] == \"SPY\",\n",
    "    [\"Date\", \"ret_1\", \"ret_std_20\", \"mom_20\"]\n",
    "].copy()\n",
    "\n",
    "spy_context = spy_context.rename(columns={\n",
    "    \"ret_1\": \"spy_ret_1\",\n",
    "    \"ret_std_20\": \"spy_vol_20\",\n",
    "    \"mom_20\": \"spy_mom_20\"\n",
    "})\n",
    "\n",
    "panel[\"spy_ret_1\"] = panel[\"Date\"].map(spy_context.set_index(\"Date\")[\"spy_ret_1\"].to_dict())\n",
    "panel[\"spy_vol_20\"] = panel[\"Date\"].map(spy_context.set_index(\"Date\")[\"spy_vol_20\"].to_dict())\n",
    "panel[\"spy_mom_20\"] = panel[\"Date\"].map(spy_context.set_index(\"Date\")[\"spy_mom_20\"].to_dict())\n",
    "vix_raw = yf.download(\"^VIX\", start=start_date, end=end_date, auto_adjust=True, progress=False)\n",
    "\n",
    "if isinstance(vix_raw.columns, pd.MultiIndex):\n",
    "    vix_raw.columns = [c[0] if isinstance(c, tuple) else c for c in vix_raw.columns]\n",
    "\n",
    "vix = vix_raw.reset_index()[[\"Date\", \"Close\"]].copy()\n",
    "vix = vix.rename(columns={\"Close\": \"vix_close\"})\n",
    "vix[\"vix_ret_1\"] = np.log(vix[\"vix_close\"]).diff()\n",
    "\n",
    "panel[\"vix_close\"] = panel[\"Date\"].map(vix.set_index(\"Date\")[\"vix_close\"].to_dict())\n",
    "panel[\"vix_ret_1\"] = panel[\"Date\"].map(vix.set_index(\"Date\")[\"vix_ret_1\"].to_dict())\n",
    "for h in [1, 5, 21]:\n",
    "    median_vol_by_day = panel.groupby(\"Date\")[f\"future_rv_{h}\"].transform(\"median\")\n",
    "    valid_mask = panel[f\"future_ret_{h}\"].notna() & panel[f\"future_rv_{h}\"].notna()\n",
    "    \n",
    "    panel[f\"quality_label_{h}\"] = np.where(\n",
    "        valid_mask,\n",
    "        (\n",
    "            (panel[f\"future_ret_{h}\"] > 0) &\n",
    "            (panel[f\"future_rv_{h}\"] < median_vol_by_day)\n",
    "        ).astype(int),\n",
    "        np.nan\n",
    "    )\n",
    "feature_cols = [\n",
    "    \"ret_1\", \"simple_ret_1\",\n",
    "    \"ret_mean_5\", \"ret_mean_10\", \"ret_mean_20\", \"ret_mean_60\",\n",
    "    \"ret_std_5\", \"ret_std_10\", \"ret_std_20\", \"ret_std_60\",\n",
    "    \"mom_5\", \"mom_10\", \"mom_20\", \"mom_60\",\n",
    "    \"hl_range\", \"oc_return\",\n",
    "    \"log_volume\", \"vol_chg_1\", \"vol_mean_20\",\n",
    "    \"rsi_14\", \"macd\", \"macd_signal\", \"macd_diff\",\n",
    "    \"bb_width\", \"atr_14\",\n",
    "    \"spy_ret_1\", \"spy_vol_20\", \"spy_mom_20\",\n",
    "    \"vix_close\", \"vix_ret_1\",\n",
    "    \"dow_sin\", \"dow_cos\", \"month_sin\", \"month_cos\"\n",
    "]\n",
    "\n",
    "target_reg_cols = [\n",
    "    \"future_rv_1\", \"future_rv_5\", \"future_rv_21\",\n",
    "    \"future_dsv_1\", \"future_dsv_5\", \"future_dsv_21\",\n",
    "    \"future_score_1\", \"future_score_5\", \"future_score_21\"\n",
    "]\n",
    "\n",
    "target_cls_cols = [\n",
    "    \"quality_label_1\", \"quality_label_5\", \"quality_label_21\"\n",
    "]\n",
    "\n",
    "needed_cols = [\"Date\", \"ticker\"] + feature_cols + target_reg_cols + target_cls_cols\n",
    "missing_cols = [c for c in needed_cols if c not in panel.columns]\n",
    "\n",
    "print(\"Missing columns:\", missing_cols)\n",
    "feature_cols = [\n",
    "    \"ret_1\", \"simple_ret_1\",\n",
    "    \"ret_mean_5\", \"ret_mean_10\", \"ret_mean_20\", \"ret_mean_60\",\n",
    "    \"ret_std_5\", \"ret_std_10\", \"ret_std_20\", \"ret_std_60\",\n",
    "    \"mom_5\", \"mom_10\", \"mom_20\", \"mom_60\",\n",
    "    \"hl_range\", \"oc_return\",\n",
    "    \"log_volume\", \"vol_chg_1\", \"vol_mean_20\",\n",
    "    \"rsi_14\", \"macd\", \"macd_signal\", \"macd_diff\",\n",
    "    \"bb_width\", \"atr_14\",\n",
    "    \"spy_ret_1\", \"spy_vol_20\", \"spy_mom_20\",\n",
    "    \"vix_close\", \"vix_ret_1\",\n",
    "    \"dow_sin\", \"dow_cos\", \"month_sin\", \"month_cos\"\n",
    "]\n",
    "\n",
    "target_reg_cols = [\n",
    "    \"future_rv_1\", \"future_rv_5\", \"future_rv_21\",\n",
    "    \"future_dsv_1\", \"future_dsv_5\", \"future_dsv_21\",\n",
    "    \"future_score_1\", \"future_score_5\", \"future_score_21\"\n",
    "]\n",
    "\n",
    "target_cls_cols = [\n",
    "    \"quality_label_1\", \"quality_label_5\", \"quality_label_21\"\n",
    "]\n",
    "\n",
    "needed_cols = [\"Date\", \"ticker\"] + feature_cols + target_reg_cols + target_cls_cols\n",
    "missing_cols = [c for c in needed_cols if c not in panel.columns]\n",
    "\n",
    "print(\"Missing columns:\", missing_cols)\n",
    "model_df = panel[needed_cols].copy()\n",
    "model_df = model_df.dropna().reset_index(drop=True)\n",
    "\n",
    "print(model_df.shape)\n",
    "model_df.head()\n",
    "train_end = \"2020-12-31\"\n",
    "val_end = \"2023-12-31\"\n",
    "\n",
    "train_df = model_df[model_df[\"Date\"] <= train_end].copy()\n",
    "val_df = model_df[(model_df[\"Date\"] > train_end) & (model_df[\"Date\"] <= val_end)].copy()\n",
    "test_df = model_df[model_df[\"Date\"] > val_end].copy()\n",
    "\n",
    "print(train_df.shape, val_df.shape, test_df.shape)\n",
    "print(train_df[\"Date\"].min(), train_df[\"Date\"].max())\n",
    "print(val_df[\"Date\"].min(), val_df[\"Date\"].max())\n",
    "print(test_df[\"Date\"].min(), test_df[\"Date\"].max())\n",
    "scaler = StandardScaler()\n",
    "\n",
    "X_train = scaler.fit_transform(train_df[feature_cols])\n",
    "X_val = scaler.transform(val_df[feature_cols])\n",
    "X_test = scaler.transform(test_df[feature_cols])\n",
    "\n",
    "y_train_rv5 = train_df[\"future_rv_5\"].values\n",
    "y_val_rv5 = val_df[\"future_rv_5\"].values\n",
    "y_test_rv5 = test_df[\"future_rv_5\"].values\n",
    "\n",
    "y_train_cls5 = train_df[\"quality_label_5\"].values\n",
    "y_val_cls5 = val_df[\"quality_label_5\"].values\n",
    "y_test_cls5 = test_df[\"quality_label_5\"].values\n",
    "def regression_metrics(y_true, y_pred, name=\"Model\"):\n",
    "    rmse = np.sqrt(mean_squared_error(y_true, y_pred))\n",
    "    mae = mean_absolute_error(y_true, y_pred)\n",
    "    r2 = r2_score(y_true, y_pred)\n",
    "    print(f\"{name}\")\n",
    "    print(f\"RMSE: {rmse:.6f}\")\n",
    "    print(f\"MAE : {mae:.6f}\")\n",
    "    print(f\"R^2 : {r2:.6f}\")\n",
    "    print(\"-\" * 40)\n",
    "\n",
    "def classification_metrics(y_true, y_pred, y_prob, name=\"Model\"):\n",
    "    acc = accuracy_score(y_true, y_pred)\n",
    "    prec = precision_score(y_true, y_pred, zero_division=0)\n",
    "    rec = recall_score(y_true, y_pred, zero_division=0)\n",
    "    f1 = f1_score(y_true, y_pred, zero_division=0)\n",
    "    auc = roc_auc_score(y_true, y_prob)\n",
    "    print(f\"{name}\")\n",
    "    print(f\"Accuracy : {acc:.6f}\")\n",
    "    print(f\"Precision: {prec:.6f}\")\n",
    "    print(f\"Recall   : {rec:.6f}\")\n",
    "    print(f\"F1       : {f1:.6f}\")\n",
    "    print(f\"ROC-AUC  : {auc:.6f}\")\n",
    "    print(\"-\" * 40)\n",
    "ridge = Ridge(alpha=1.0)\n",
    "ridge.fit(X_train, y_train_rv5)\n",
    "\n",
    "val_pred_ridge = ridge.predict(X_val)\n",
    "test_pred_ridge = ridge.predict(X_test)\n",
    "\n",
    "regression_metrics(y_val_rv5, val_pred_ridge, \"Ridge Validation\")\n",
    "regression_metrics(y_test_rv5, test_pred_ridge, \"Ridge Test\")\n",
    "logit = LogisticRegression(max_iter=2000, class_weight=\"balanced\")\n",
    "logit.fit(X_train, y_train_cls5)\n",
    "\n",
    "val_prob_logit = logit.predict_proba(X_val)[:, 1]\n",
    "test_prob_logit = logit.predict_proba(X_test)[:, 1]\n",
    "\n",
    "val_pred_logit = (val_prob_logit >= 0.5).astype(int)\n",
    "test_pred_logit = (test_prob_logit >= 0.5).astype(int)\n",
    "\n",
    "classification_metrics(y_val_cls5, val_pred_logit, val_prob_logit, \"Logistic Validation\")\n",
    "classification_metrics(y_test_cls5, test_pred_logit, test_prob_logit, \"Logistic Test\")\n",
    "rf_reg = RandomForestRegressor(\n",
    "    n_estimators=300,\n",
    "    max_depth=8,\n",
    "    min_samples_leaf=5,\n",
    "    random_state=SEED,\n",
    "    n_jobs=-1\n",
    ")\n",
    "rf_reg.fit(X_train, y_train_rv5)\n",
    "\n",
    "val_pred_rf = rf_reg.predict(X_val)\n",
    "test_pred_rf = rf_reg.predict(X_test)\n",
    "\n",
    "regression_metrics(y_val_rv5, val_pred_rf, \"Random Forest Validation\")\n",
    "regression_metrics(y_test_rv5, test_pred_rf, \"Random Forest Test\")\n",
    "rf_cls = RandomForestClassifier(\n",
    "    n_estimators=300,\n",
    "    max_depth=8,\n",
    "    min_samples_leaf=5,\n",
    "    random_state=SEED,\n",
    "    n_jobs=-1,\n",
    "    class_weight=\"balanced\"\n",
    ")\n",
    "rf_cls.fit(X_train, y_train_cls5)\n",
    "\n",
    "val_prob_rf = rf_cls.predict_proba(X_val)[:, 1]\n",
    "test_prob_rf = rf_cls.predict_proba(X_test)[:, 1]\n",
    "\n",
    "val_pred_rf_cls = (val_prob_rf >= 0.5).astype(int)\n",
    "test_pred_rf_cls = (test_prob_rf >= 0.5).astype(int)\n",
    "\n",
    "classification_metrics(y_val_cls5, val_pred_rf_cls, val_prob_rf, \"Random Forest Validation\")\n",
    "classification_metrics(y_test_cls5, test_pred_rf_cls, test_prob_rf, \"Random Forest Test\")\n",
    "sample_plot = test_df[[\"Date\", \"ticker\"]].copy()\n",
    "sample_plot[\"actual_rv5\"] = y_test_rv5\n",
    "sample_plot[\"pred_ridge\"] = test_pred_ridge\n",
    "sample_plot[\"pred_rf\"] = test_pred_rf\n",
    "\n",
    "sample_asset = \"SPY\"\n",
    "plot_df = sample_plot[sample_plot[\"ticker\"] == sample_asset].sort_values(\"Date\").tail(200)\n",
    "\n",
    "plt.figure(figsize=(14, 5))\n",
    "plt.plot(plot_df[\"Date\"], plot_df[\"actual_rv5\"], label=\"Actual\")\n",
    "plt.plot(plot_df[\"Date\"], plot_df[\"pred_ridge\"], label=\"Ridge\")\n",
    "plt.plot(plot_df[\"Date\"], plot_df[\"pred_rf\"], label=\"Random Forest\")\n",
    "plt.title(f\"{sample_asset}: 5-Day Ahead Realized Volatility\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "train_seq_df = train_df.copy()\n",
    "val_seq_df = val_df.copy()\n",
    "test_seq_df = test_df.copy()\n",
    "\n",
    "seq_scaler = StandardScaler()\n",
    "train_seq_df[feature_cols] = seq_scaler.fit_transform(train_seq_df[feature_cols])\n",
    "val_seq_df[feature_cols] = seq_scaler.transform(val_seq_df[feature_cols])\n",
    "test_seq_df[feature_cols] = seq_scaler.transform(test_seq_df[feature_cols])\n",
    "\n",
    "print(train_seq_df.shape, val_seq_df.shape, test_seq_df.shape)\n",
    "class PanelSequenceDataset(Dataset):\n",
    "    def __init__(self, df, feature_cols, target_col, lookback=60):\n",
    "        self.X = []\n",
    "        self.y = []\n",
    "        self.meta = []\n",
    "        \n",
    "        for ticker, g in df.groupby(\"ticker\"):\n",
    "            g = g.sort_values(\"Date\").reset_index(drop=True)\n",
    "            \n",
    "            feat = g[feature_cols].values.astype(np.float32)\n",
    "            targ = g[target_col].values.astype(np.float32)\n",
    "            dates = g[\"Date\"].values\n",
    "            \n",
    "            for i in range(lookback, len(g)):\n",
    "                self.X.append(feat[i-lookback:i])\n",
    "                self.y.append(targ[i])\n",
    "                self.meta.append((ticker, dates[i]))\n",
    "        \n",
    "        self.X = np.array(self.X, dtype=np.float32)\n",
    "        self.y = np.array(self.y, dtype=np.float32)\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.y)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        return self.X[idx], self.y[idx]\n",
    "lookback = 60\n",
    "\n",
    "train_dataset_rv = PanelSequenceDataset(\n",
    "    train_seq_df, feature_cols, target_col=\"future_rv_5\", lookback=lookback\n",
    ")\n",
    "val_dataset_rv = PanelSequenceDataset(\n",
    "    val_seq_df, feature_cols, target_col=\"future_rv_5\", lookback=lookback\n",
    ")\n",
    "test_dataset_rv = PanelSequenceDataset(\n",
    "    test_seq_df, feature_cols, target_col=\"future_rv_5\", lookback=lookback\n",
    ")\n",
    "\n",
    "print(\"Train sequences:\", len(train_dataset_rv))\n",
    "print(\"Val sequences  :\", len(val_dataset_rv))\n",
    "print(\"Test sequences :\", len(test_dataset_rv))\n",
    "x_sample, y_sample = train_dataset_rv[0]\n",
    "print(\"X shape:\", x_sample.shape)   # should be (lookback, num_features)\n",
    "print(\"y value:\", y_sample)\n",
    "train_loader = DataLoader(train_dataset_rv, batch_size=128, shuffle=True)\n",
    "val_loader = DataLoader(val_dataset_rv, batch_size=256, shuffle=False)\n",
    "test_loader = DataLoader(test_dataset_rv, batch_size=256, shuffle=False)\n",
    "class LSTMRegressor(nn.Module):\n",
    "    def __init__(self, input_dim, hidden_dim=64, num_layers=2, dropout=0.2):\n",
    "        super().__init__()\n",
    "        \n",
    "        self.lstm = nn.LSTM(\n",
    "            input_size=input_dim,\n",
    "            hidden_size=hidden_dim,\n",
    "            num_layers=num_layers,\n",
    "            batch_first=True,\n",
    "            dropout=dropout\n",
    "        )\n",
    "        \n",
    "        self.attn = nn.Linear(hidden_dim, 1)\n",
    "        \n",
    "        self.fc = nn.Sequential(\n",
    "            nn.Linear(hidden_dim, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(dropout),\n",
    "            nn.Linear(32, 1)\n",
    "        )\n",
    "    \n",
    "    def forward(self, x):\n",
    "        out, _ = self.lstm(x)                  # [B, T, H]\n",
    "        attn_weights = torch.softmax(self.attn(out), dim=1)   # [B, T, 1]\n",
    "        context = torch.sum(attn_weights * out, dim=1)        # [B, H]\n",
    "        pred = self.fc(context).squeeze(-1)                   # [B]\n",
    "        return pred\n",
    "def train_lstm_regressor(model, train_loader, val_loader, epochs=15, lr=1e-3):\n",
    "    model = model.to(DEVICE)\n",
    "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
    "    criterion = nn.MSELoss()\n",
    "    \n",
    "    best_val_loss = np.inf\n",
    "    best_state = None\n",
    "    \n",
    "    train_losses = []\n",
    "    val_losses = []\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        running_train_loss = 0.0\n",
    "        \n",
    "        for xb, yb in train_loader:\n",
    "            xb = xb.to(DEVICE)\n",
    "            yb = yb.to(DEVICE)\n",
    "            \n",
    "            optimizer.zero_grad()\n",
    "            preds = model(xb)\n",
    "            loss = criterion(preds, yb)\n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            \n",
    "            running_train_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        epoch_train_loss = running_train_loss / len(train_loader.dataset)\n",
    "        train_losses.append(epoch_train_loss)\n",
    "        \n",
    "        model.eval()\n",
    "        running_val_loss = 0.0\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            for xb, yb in val_loader:\n",
    "                xb = xb.to(DEVICE)\n",
    "                yb = yb.to(DEVICE)\n",
    "                preds = model(xb)\n",
    "                loss = criterion(preds, yb)\n",
    "                running_val_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        epoch_val_loss = running_val_loss / len(val_loader.dataset)\n",
    "        val_losses.append(epoch_val_loss)\n",
    "        \n",
    "        print(f\"Epoch {epoch+1:02d} | Train Loss: {epoch_train_loss:.6f} | Val Loss: {epoch_val_loss:.6f}\")\n",
    "        \n",
    "        if epoch_val_loss < best_val_loss:\n",
    "            best_val_loss = epoch_val_loss\n",
    "            best_state = model.state_dict()\n",
    "    \n",
    "    model.load_state_dict(best_state)\n",
    "    return model, train_losses, val_losses\n",
    "lstm_reg = LSTMRegressor(\n",
    "    input_dim=len(feature_cols),\n",
    "    hidden_dim=64,\n",
    "    num_layers=2,\n",
    "    dropout=0.2\n",
    ")\n",
    "\n",
    "lstm_reg, train_losses, val_losses = train_lstm_regressor(\n",
    "    lstm_reg,\n",
    "    train_loader,\n",
    "    val_loader,\n",
    "    epochs=15,\n",
    "    lr=1e-3\n",
    ")\n",
    "def predict_regression(model, loader):\n",
    "    model.eval()\n",
    "    preds = []\n",
    "    trues = []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for xb, yb in loader:\n",
    "            xb = xb.to(DEVICE)\n",
    "            out = model(xb).cpu().numpy()\n",
    "            preds.extend(out)\n",
    "            trues.extend(yb.numpy())\n",
    "    \n",
    "    return np.array(trues), np.array(preds)\n",
    "y_val_true_lstm, y_val_pred_lstm = predict_regression(lstm_reg, val_loader)\n",
    "y_test_true_lstm, y_test_pred_lstm = predict_regression(lstm_reg, test_loader)\n",
    "\n",
    "regression_metrics(y_val_true_lstm, y_val_pred_lstm, \"LSTM Validation\")\n",
    "regression_metrics(y_test_true_lstm, y_test_pred_lstm, \"LSTM Test\")\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(train_losses, label=\"Train Loss\")\n",
    "plt.plot(val_losses, label=\"Validation Loss\")\n",
    "plt.title(\"LSTM Training Curve\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"MSE Loss\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "test_meta = pd.DataFrame(test_dataset_rv.meta, columns=[\"ticker\", \"Date\"])\n",
    "test_meta[\"Date\"] = pd.to_datetime(test_meta[\"Date\"])\n",
    "test_meta[\"actual_rv5\"] = y_test_true_lstm\n",
    "test_meta[\"pred_lstm\"] = y_test_pred_lstm\n",
    "\n",
    "plot_lstm_df = test_meta[test_meta[\"ticker\"] == \"SPY\"].sort_values(\"Date\").tail(200)\n",
    "\n",
    "plt.figure(figsize=(14, 5))\n",
    "plt.plot(plot_lstm_df[\"Date\"], plot_lstm_df[\"actual_rv5\"], label=\"Actual\")\n",
    "plt.plot(plot_lstm_df[\"Date\"], plot_lstm_df[\"pred_lstm\"], label=\"LSTM\")\n",
    "plt.title(\"SPY: 5-Day Ahead Realized Volatility (LSTM)\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "summary_rows = []\n",
    "\n",
    "def get_reg_metrics_dict(y_true, y_pred, model_name):\n",
    "    return {\n",
    "        \"Model\": model_name,\n",
    "        \"RMSE\": np.sqrt(mean_squared_error(y_true, y_pred)),\n",
    "        \"MAE\": mean_absolute_error(y_true, y_pred),\n",
    "        \"R2\": r2_score(y_true, y_pred)\n",
    "    }\n",
    "\n",
    "summary_rows.append(get_reg_metrics_dict(y_test_rv5, test_pred_ridge, \"Ridge\"))\n",
    "summary_rows.append(get_reg_metrics_dict(y_test_rv5, test_pred_rf, \"Random Forest\"))\n",
    "summary_rows.append(get_reg_metrics_dict(y_test_true_lstm, y_test_pred_lstm, \"LSTM\"))\n",
    "\n",
    "summary_df = pd.DataFrame(summary_rows)\n",
    "summary_df\n",
    "summary_rows = []\n",
    "\n",
    "def get_reg_metrics_dict(y_true, y_pred, model_name):\n",
    "    return {\n",
    "        \"Model\": model_name,\n",
    "        \"RMSE\": np.sqrt(mean_squared_error(y_true, y_pred)),\n",
    "        \"MAE\": mean_absolute_error(y_true, y_pred),\n",
    "        \"R2\": r2_score(y_true, y_pred)\n",
    "    }\n",
    "\n",
    "summary_rows.append(get_reg_metrics_dict(y_test_rv5, test_pred_ridge, \"Ridge\"))\n",
    "summary_rows.append(get_reg_metrics_dict(y_test_rv5, test_pred_rf, \"Random Forest\"))\n",
    "summary_rows.append(get_reg_metrics_dict(y_test_true_lstm, y_test_pred_lstm, \"LSTM\"))\n",
    "\n",
    "summary_df = pd.DataFrame(summary_rows)\n",
    "summary_df\n",
    "multitask_targets = [\n",
    "    \"future_rv_5\",\n",
    "    \"future_dsv_5\",\n",
    "    \"future_score_5\",\n",
    "    \"quality_label_5\"\n",
    "]\n",
    "\n",
    "class MultiTaskPanelSequenceDataset(Dataset):\n",
    "    def __init__(self, df, feature_cols, target_cols, lookback=60):\n",
    "        self.X = []\n",
    "        self.y_reg = []\n",
    "        self.y_cls = []\n",
    "        self.meta = []\n",
    "        \n",
    "        reg_cols = [\"future_rv_5\", \"future_dsv_5\", \"future_score_5\"]\n",
    "        cls_col = \"quality_label_5\"\n",
    "        \n",
    "        for ticker, g in df.groupby(\"ticker\"):\n",
    "            g = g.sort_values(\"Date\").reset_index(drop=True)\n",
    "            \n",
    "            feat = g[feature_cols].values.astype(np.float32)\n",
    "            y_reg = g[reg_cols].values.astype(np.float32)\n",
    "            y_cls = g[cls_col].values.astype(np.float32)\n",
    "            dates = g[\"Date\"].values\n",
    "            \n",
    "            for i in range(lookback, len(g)):\n",
    "                self.X.append(feat[i-lookback:i])\n",
    "                self.y_reg.append(y_reg[i])\n",
    "                self.y_cls.append(y_cls[i])\n",
    "                self.meta.append((ticker, dates[i]))\n",
    "        \n",
    "        self.X = np.array(self.X, dtype=np.float32)\n",
    "        self.y_reg = np.array(self.y_reg, dtype=np.float32)\n",
    "        self.y_cls = np.array(self.y_cls, dtype=np.float32)\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.y_cls)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        return self.X[idx], self.y_reg[idx], self.y_cls[idx]\n",
    "multitask_targets = [\n",
    "    \"future_rv_5\",\n",
    "    \"future_dsv_5\",\n",
    "    \"future_score_5\",\n",
    "    \"quality_label_5\"\n",
    "]\n",
    "train_dataset_mt = MultiTaskPanelSequenceDataset(\n",
    "    train_seq_df, feature_cols, multitask_targets, lookback=lookback\n",
    ")\n",
    "val_dataset_mt = MultiTaskPanelSequenceDataset(\n",
    "    val_seq_df, feature_cols, multitask_targets, lookback=lookback\n",
    ")\n",
    "test_dataset_mt = MultiTaskPanelSequenceDataset(\n",
    "    test_seq_df, feature_cols, multitask_targets, lookback=lookback\n",
    ")\n",
    "\n",
    "print(\"Train multitask sequences:\", len(train_dataset_mt))\n",
    "print(\"Val multitask sequences  :\", len(val_dataset_mt))\n",
    "print(\"Test multitask sequences :\", len(test_dataset_mt))\n",
    "\n",
    "x_mt, y_reg_mt, y_cls_mt = train_dataset_mt[0]\n",
    "\n",
    "print(\"X shape     :\", x_mt.shape)\n",
    "print(\"y_reg shape :\", y_reg_mt.shape)\n",
    "print(\"y_reg value :\", y_reg_mt)\n",
    "print(\"y_cls value :\", y_cls_mt)\n",
    "train_loader_mt = DataLoader(train_dataset_mt, batch_size=128, shuffle=True)\n",
    "val_loader_mt = DataLoader(val_dataset_mt, batch_size=256, shuffle=False)\n",
    "test_loader_mt = DataLoader(test_dataset_mt, batch_size=256, shuffle=False)\n",
    "class MultiTaskLSTMAttention(nn.Module):\n",
    "    def __init__(self, input_dim, hidden_dim=64, num_layers=2, dropout=0.2):\n",
    "        super().__init__()\n",
    "        \n",
    "        self.lstm = nn.LSTM(\n",
    "            input_size=input_dim,\n",
    "            hidden_size=hidden_dim,\n",
    "            num_layers=num_layers,\n",
    "            batch_first=True,\n",
    "            dropout=dropout\n",
    "        )\n",
    "        \n",
    "        self.attn = nn.Linear(hidden_dim, 1)\n",
    "        \n",
    "        self.shared = nn.Sequential(\n",
    "            nn.Linear(hidden_dim, 64),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(dropout)\n",
    "        )\n",
    "        \n",
    "        # Regression heads\n",
    "        self.rv_head = nn.Sequential(\n",
    "            nn.Linear(64, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(32, 1)\n",
    "        )\n",
    "        \n",
    "        self.dsv_head = nn.Sequential(\n",
    "            nn.Linear(64, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(32, 1)\n",
    "        )\n",
    "        \n",
    "        self.score_head = nn.Sequential(\n",
    "            nn.Linear(64, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(32, 1)\n",
    "        )\n",
    "        \n",
    "        # Classification head\n",
    "        self.cls_head = nn.Sequential(\n",
    "            nn.Linear(64, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(32, 1)\n",
    "        )\n",
    "    \n",
    "    def forward(self, x):\n",
    "        out, _ = self.lstm(x)                           # [B, T, H]\n",
    "        attn_weights = torch.softmax(self.attn(out), dim=1)\n",
    "        context = torch.sum(attn_weights * out, dim=1) # [B, H]\n",
    "        z = self.shared(context)                        # [B, 64]\n",
    "        \n",
    "        rv_pred = self.rv_head(z).squeeze(-1)\n",
    "        dsv_pred = self.dsv_head(z).squeeze(-1)\n",
    "        score_pred = self.score_head(z).squeeze(-1)\n",
    "        cls_logit = self.cls_head(z).squeeze(-1)\n",
    "        \n",
    "        return rv_pred, dsv_pred, score_pred, cls_logit\n",
    "def train_multitask_model(\n",
    "    model,\n",
    "    train_loader,\n",
    "    val_loader,\n",
    "    epochs=20,\n",
    "    lr=1e-3,\n",
    "    w_rv=1.0,\n",
    "    w_dsv=1.0,\n",
    "    w_score=0.5,\n",
    "    w_cls=1.0\n",
    "):\n",
    "    model = model.to(DEVICE)\n",
    "    \n",
    "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
    "    mse_loss = nn.MSELoss()\n",
    "    bce_loss = nn.BCEWithLogitsLoss()\n",
    "    \n",
    "    best_val_loss = np.inf\n",
    "    best_state = None\n",
    "    \n",
    "    train_losses = []\n",
    "    val_losses = []\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        running_train_loss = 0.0\n",
    "        \n",
    "        for xb, y_regb, y_clsb in train_loader:\n",
    "            xb = xb.to(DEVICE)\n",
    "            y_regb = y_regb.to(DEVICE)\n",
    "            y_clsb = y_clsb.to(DEVICE)\n",
    "            \n",
    "            optimizer.zero_grad()\n",
    "            \n",
    "            rv_pred, dsv_pred, score_pred, cls_logit = model(xb)\n",
    "            \n",
    "            loss_rv = mse_loss(rv_pred, y_regb[:, 0])\n",
    "            loss_dsv = mse_loss(dsv_pred, y_regb[:, 1])\n",
    "            loss_score = mse_loss(score_pred, y_regb[:, 2])\n",
    "            loss_cls = bce_loss(cls_logit, y_clsb)\n",
    "            \n",
    "            loss = (\n",
    "                w_rv * loss_rv +\n",
    "                w_dsv * loss_dsv +\n",
    "                w_score * loss_score +\n",
    "                w_cls * loss_cls\n",
    "            )\n",
    "            \n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            \n",
    "            running_train_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        epoch_train_loss = running_train_loss / len(train_loader.dataset)\n",
    "        train_losses.append(epoch_train_loss)\n",
    "        \n",
    "        model.eval()\n",
    "        running_val_loss = 0.0\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            for xb, y_regb, y_clsb in val_loader:\n",
    "                xb = xb.to(DEVICE)\n",
    "                y_regb = y_regb.to(DEVICE)\n",
    "                y_clsb = y_clsb.to(DEVICE)\n",
    "                \n",
    "                rv_pred, dsv_pred, score_pred, cls_logit = model(xb)\n",
    "                \n",
    "                loss_rv = mse_loss(rv_pred, y_regb[:, 0])\n",
    "                loss_dsv = mse_loss(dsv_pred, y_regb[:, 1])\n",
    "                loss_score = mse_loss(score_pred, y_regb[:, 2])\n",
    "                loss_cls = bce_loss(cls_logit, y_clsb)\n",
    "                \n",
    "                loss = (\n",
    "                    w_rv * loss_rv +\n",
    "                    w_dsv * loss_dsv +\n",
    "                    w_score * loss_score +\n",
    "                    w_cls * loss_cls\n",
    "                )\n",
    "                \n",
    "                running_val_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        epoch_val_loss = running_val_loss / len(val_loader.dataset)\n",
    "        val_losses.append(epoch_val_loss)\n",
    "        \n",
    "        print(f\"Epoch {epoch+1:02d} | Train Loss: {epoch_train_loss:.6f} | Val Loss: {epoch_val_loss:.6f}\")\n",
    "        \n",
    "        if epoch_val_loss < best_val_loss:\n",
    "            best_val_loss = epoch_val_loss\n",
    "            best_state = model.state_dict()\n",
    "    \n",
    "    model.load_state_dict(best_state)\n",
    "    return model, train_losses, val_losses\n",
    "mt_model = MultiTaskLSTMAttention(\n",
    "    input_dim=len(feature_cols),\n",
    "    hidden_dim=64,\n",
    "    num_layers=2,\n",
    "    dropout=0.2\n",
    ")\n",
    "\n",
    "mt_model, mt_train_losses, mt_val_losses = train_multitask_model(\n",
    "    mt_model,\n",
    "    train_loader_mt,\n",
    "    val_loader_mt,\n",
    "    epochs=20,\n",
    "    lr=1e-3,\n",
    "    w_rv=1.0,\n",
    "    w_dsv=1.0,\n",
    "    w_score=0.5,\n",
    "    w_cls=1.0\n",
    ")\n",
    "def predict_multitask(model, loader):\n",
    "    model.eval()\n",
    "    \n",
    "    rv_preds, dsv_preds, score_preds, cls_probs = [], [], [], []\n",
    "    y_reg_true, y_cls_true = [], []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for xb, y_regb, y_clsb in loader:\n",
    "            xb = xb.to(DEVICE)\n",
    "            \n",
    "            rv_pred, dsv_pred, score_pred, cls_logit = model(xb)\n",
    "            cls_prob = torch.sigmoid(cls_logit)\n",
    "            \n",
    "            rv_preds.extend(rv_pred.cpu().numpy())\n",
    "            dsv_preds.extend(dsv_pred.cpu().numpy())\n",
    "            score_preds.extend(score_pred.cpu().numpy())\n",
    "            cls_probs.extend(cls_prob.cpu().numpy())\n",
    "            \n",
    "            y_reg_true.extend(y_regb.numpy())\n",
    "            y_cls_true.extend(y_clsb.numpy())\n",
    "    \n",
    "    y_reg_true = np.array(y_reg_true)\n",
    "    y_cls_true = np.array(y_cls_true)\n",
    "    \n",
    "    return {\n",
    "        \"rv_pred\": np.array(rv_preds),\n",
    "        \"dsv_pred\": np.array(dsv_preds),\n",
    "        \"score_pred\": np.array(score_preds),\n",
    "        \"cls_prob\": np.array(cls_probs),\n",
    "        \"y_reg_true\": y_reg_true,\n",
    "        \"y_cls_true\": y_cls_true\n",
    "    }\n",
    "val_mt = predict_multitask(mt_model, val_loader_mt)\n",
    "test_mt = predict_multitask(mt_model, test_loader_mt)\n",
    "\n",
    "print(\"Validation: future_rv_5\")\n",
    "regression_metrics(val_mt[\"y_reg_true\"][:, 0], val_mt[\"rv_pred\"], \"MT-LSTM Validation RV\")\n",
    "\n",
    "print(\"Test: future_rv_5\")\n",
    "regression_metrics(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"], \"MT-LSTM Test RV\")\n",
    "\n",
    "print(\"Validation: future_dsv_5\")\n",
    "regression_metrics(val_mt[\"y_reg_true\"][:, 1], val_mt[\"dsv_pred\"], \"MT-LSTM Validation DSV\")\n",
    "\n",
    "print(\"Test: future_dsv_5\")\n",
    "regression_metrics(test_mt[\"y_reg_true\"][:, 1], test_mt[\"dsv_pred\"], \"MT-LSTM Test DSV\")\n",
    "\n",
    "print(\"Validation: future_score_5\")\n",
    "regression_metrics(val_mt[\"y_reg_true\"][:, 2], val_mt[\"score_pred\"], \"MT-LSTM Validation Score\")\n",
    "\n",
    "print(\"Test: future_score_5\")\n",
    "regression_metrics(test_mt[\"y_reg_true\"][:, 2], test_mt[\"score_pred\"], \"MT-LSTM Test Score\")\n",
    "\n",
    "val_cls_pred = (val_mt[\"cls_prob\"] >= 0.5).astype(int)\n",
    "test_cls_pred = (test_mt[\"cls_prob\"] >= 0.5).astype(int)\n",
    "\n",
    "print(\"Validation: quality_label_5\")\n",
    "classification_metrics(val_mt[\"y_cls_true\"], val_cls_pred, val_mt[\"cls_prob\"], \"MT-LSTM Validation CLS\")\n",
    "\n",
    "print(\"Test: quality_label_5\")\n",
    "classification_metrics(test_mt[\"y_cls_true\"], test_cls_pred, test_mt[\"cls_prob\"], \"MT-LSTM Test CLS\")\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(mt_train_losses, label=\"Train Loss\")\n",
    "plt.plot(mt_val_losses, label=\"Validation Loss\")\n",
    "plt.title(\"Multi-Task LSTM Training Curve\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Combined Loss\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "mt_summary_rows = []\n",
    "\n",
    "mt_summary_rows.append({\n",
    "    \"Model\": \"Ridge\",\n",
    "    \"Task\": \"future_rv_5\",\n",
    "    \"RMSE\": np.sqrt(mean_squared_error(y_test_rv5, test_pred_ridge)),\n",
    "    \"MAE\": mean_absolute_error(y_test_rv5, test_pred_ridge),\n",
    "    \"R2\": r2_score(y_test_rv5, test_pred_ridge)\n",
    "})\n",
    "\n",
    "mt_summary_rows.append({\n",
    "    \"Model\": \"Random Forest\",\n",
    "    \"Task\": \"future_rv_5\",\n",
    "    \"RMSE\": np.sqrt(mean_squared_error(y_test_rv5, test_pred_rf)),\n",
    "    \"MAE\": mean_absolute_error(y_test_rv5, test_pred_rf),\n",
    "    \"R2\": r2_score(y_test_rv5, test_pred_rf)\n",
    "})\n",
    "\n",
    "mt_summary_rows.append({\n",
    "    \"Model\": \"Single-Task LSTM\",\n",
    "    \"Task\": \"future_rv_5\",\n",
    "    \"RMSE\": np.sqrt(mean_squared_error(y_test_true_lstm, y_test_pred_lstm)),\n",
    "    \"MAE\": mean_absolute_error(y_test_true_lstm, y_test_pred_lstm),\n",
    "    \"R2\": r2_score(y_test_true_lstm, y_test_pred_lstm)\n",
    "})\n",
    "\n",
    "mt_summary_rows.append({\n",
    "    \"Model\": \"Multi-Task LSTM\",\n",
    "    \"Task\": \"future_rv_5\",\n",
    "    \"RMSE\": np.sqrt(mean_squared_error(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"])),\n",
    "    \"MAE\": mean_absolute_error(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"]),\n",
    "    \"R2\": r2_score(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"])\n",
    "})\n",
    "\n",
    "mt_summary_df = pd.DataFrame(mt_summary_rows)\n",
    "mt_summary_df\n",
    "cls_summary_rows = []\n",
    "\n",
    "cls_summary_rows.append({\n",
    "    \"Model\": \"Logistic Regression\",\n",
    "    \"Accuracy\": accuracy_score(y_test_cls5, test_pred_logit),\n",
    "    \"Precision\": precision_score(y_test_cls5, test_pred_logit, zero_division=0),\n",
    "    \"Recall\": recall_score(y_test_cls5, test_pred_logit, zero_division=0),\n",
    "    \"F1\": f1_score(y_test_cls5, test_pred_logit, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(y_test_cls5, test_prob_logit)\n",
    "})\n",
    "\n",
    "cls_summary_rows.append({\n",
    "    \"Model\": \"Random Forest\",\n",
    "    \"Accuracy\": accuracy_score(y_test_cls5, test_pred_rf_cls),\n",
    "    \"Precision\": precision_score(y_test_cls5, test_pred_rf_cls, zero_division=0),\n",
    "    \"Recall\": recall_score(y_test_cls5, test_pred_rf_cls, zero_division=0),\n",
    "    \"F1\": f1_score(y_test_cls5, test_pred_rf_cls, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(y_test_cls5, test_prob_rf)\n",
    "})\n",
    "\n",
    "cls_summary_rows.append({\n",
    "    \"Model\": \"Multi-Task LSTM\",\n",
    "    \"Accuracy\": accuracy_score(test_mt[\"y_cls_true\"], test_cls_pred),\n",
    "    \"Precision\": precision_score(test_mt[\"y_cls_true\"], test_cls_pred, zero_division=0),\n",
    "    \"Recall\": recall_score(test_mt[\"y_cls_true\"], test_cls_pred, zero_division=0),\n",
    "    \"F1\": f1_score(test_mt[\"y_cls_true\"], test_cls_pred, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(test_mt[\"y_cls_true\"], test_mt[\"cls_prob\"])\n",
    "})\n",
    "\n",
    "cls_summary_df = pd.DataFrame(cls_summary_rows)\n",
    "cls_summary_df\n",
    "test_meta_mt = pd.DataFrame(test_dataset_mt.meta, columns=[\"ticker\", \"Date\"])\n",
    "test_meta_mt[\"Date\"] = pd.to_datetime(test_meta_mt[\"Date\"])\n",
    "test_meta_mt[\"actual_rv5\"] = test_mt[\"y_reg_true\"][:, 0]\n",
    "test_meta_mt[\"pred_mt_rv5\"] = test_mt[\"rv_pred\"]\n",
    "\n",
    "plot_mt_df = test_meta_mt[test_meta_mt[\"ticker\"] == \"SPY\"].sort_values(\"Date\").tail(200)\n",
    "\n",
    "plt.figure(figsize=(14, 5))\n",
    "plt.plot(plot_mt_df[\"Date\"], plot_mt_df[\"actual_rv5\"], label=\"Actual\")\n",
    "plt.plot(plot_mt_df[\"Date\"], plot_mt_df[\"pred_mt_rv5\"], label=\"Multi-Task LSTM\")\n",
    "plt.title(\"SPY: 5-Day Ahead Realized Volatility (Multi-Task LSTM)\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "#FOR BETTER MULTIMODEL PERFORMANCE\n",
    "test_meta_mt = pd.DataFrame(test_dataset_mt.meta, columns=[\"ticker\", \"Date\"])\n",
    "test_meta_mt[\"Date\"] = pd.to_datetime(test_meta_mt[\"Date\"])\n",
    "test_meta_mt[\"actual_rv5\"] = test_mt[\"y_reg_true\"][:, 0]\n",
    "test_meta_mt[\"pred_mt_rv5\"] = test_mt[\"rv_pred\"]\n",
    "\n",
    "plot_mt_df = test_meta_mt[test_meta_mt[\"ticker\"] == \"SPY\"].sort_values(\"Date\").tail(200)\n",
    "\n",
    "plt.figure(figsize=(14, 5))\n",
    "plt.plot(plot_mt_df[\"Date\"], plot_mt_df[\"actual_rv5\"], label=\"Actual\")\n",
    "plt.plot(plot_mt_df[\"Date\"], plot_mt_df[\"pred_mt_rv5\"], label=\"Multi-Task LSTM\")\n",
    "plt.title(\"SPY: 5-Day Ahead Realized Volatility (Multi-Task LSTM)\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "mt_reg_cols = [\"future_rv_5\", \"future_dsv_5\", \"future_score_5\"]\n",
    "\n",
    "target_means = train_df[mt_reg_cols].mean()\n",
    "target_stds = train_df[mt_reg_cols].std().replace(0, 1.0)\n",
    "\n",
    "print(\"Target means:\")\n",
    "print(target_means)\n",
    "print(\"\\nTarget stds:\")\n",
    "print(target_stds)\n",
    "train_mt_df = train_seq_df.copy()\n",
    "val_mt_df = val_seq_df.copy()\n",
    "test_mt_df = test_seq_df.copy()\n",
    "\n",
    "for col in mt_reg_cols:\n",
    "    train_mt_df[col + \"_z\"] = (train_mt_df[col] - target_means[col]) / target_stds[col]\n",
    "    val_mt_df[col + \"_z\"] = (val_mt_df[col] - target_means[col]) / target_stds[col]\n",
    "    test_mt_df[col + \"_z\"] = (test_mt_df[col] - target_means[col]) / target_stds[col]\n",
    "\n",
    "train_mt_df[[\"future_rv_5\", \"future_rv_5_z\", \"future_dsv_5\", \"future_dsv_5_z\", \"future_score_5\", \"future_score_5_z\"]].head()\n",
    "class FixedMultiTaskPanelSequenceDataset(Dataset):\n",
    "    def __init__(self, df, feature_cols, lookback=60):\n",
    "        self.X = []\n",
    "        self.y_reg_z = []\n",
    "        self.y_reg_raw = []\n",
    "        self.y_cls = []\n",
    "        self.meta = []\n",
    "        \n",
    "        reg_z_cols = [\"future_rv_5_z\", \"future_dsv_5_z\", \"future_score_5_z\"]\n",
    "        reg_raw_cols = [\"future_rv_5\", \"future_dsv_5\", \"future_score_5\"]\n",
    "        cls_col = \"quality_label_5\"\n",
    "        \n",
    "        for ticker, g in df.groupby(\"ticker\"):\n",
    "            g = g.sort_values(\"Date\").reset_index(drop=True)\n",
    "            \n",
    "            feat = g[feature_cols].values.astype(np.float32)\n",
    "            y_reg_z = g[reg_z_cols].values.astype(np.float32)\n",
    "            y_reg_raw = g[reg_raw_cols].values.astype(np.float32)\n",
    "            y_cls = g[cls_col].values.astype(np.float32)\n",
    "            dates = g[\"Date\"].values\n",
    "            \n",
    "            for i in range(lookback, len(g)):\n",
    "                self.X.append(feat[i-lookback:i])\n",
    "                self.y_reg_z.append(y_reg_z[i])\n",
    "                self.y_reg_raw.append(y_reg_raw[i])\n",
    "                self.y_cls.append(y_cls[i])\n",
    "                self.meta.append((ticker, dates[i]))\n",
    "        \n",
    "        self.X = np.array(self.X, dtype=np.float32)\n",
    "        self.y_reg_z = np.array(self.y_reg_z, dtype=np.float32)\n",
    "        self.y_reg_raw = np.array(self.y_reg_raw, dtype=np.float32)\n",
    "        self.y_cls = np.array(self.y_cls, dtype=np.float32)\n",
    "    \n",
    "    def __len__(self):\n",
    "        return len(self.y_cls)\n",
    "    \n",
    "    def __getitem__(self, idx):\n",
    "        return self.X[idx], self.y_reg_z[idx], self.y_reg_raw[idx], self.y_cls[idx]\n",
    "train_dataset_mt_fix = FixedMultiTaskPanelSequenceDataset(train_mt_df, feature_cols, lookback=lookback)\n",
    "val_dataset_mt_fix = FixedMultiTaskPanelSequenceDataset(val_mt_df, feature_cols, lookback=lookback)\n",
    "test_dataset_mt_fix = FixedMultiTaskPanelSequenceDataset(test_mt_df, feature_cols, lookback=lookback)\n",
    "\n",
    "print(\"Train:\", len(train_dataset_mt_fix))\n",
    "print(\"Val  :\", len(val_dataset_mt_fix))\n",
    "print(\"Test :\", len(test_dataset_mt_fix))\n",
    "\n",
    "train_loader_mt_fix = DataLoader(train_dataset_mt_fix, batch_size=128, shuffle=True)\n",
    "val_loader_mt_fix = DataLoader(val_dataset_mt_fix, batch_size=256, shuffle=False)\n",
    "test_loader_mt_fix = DataLoader(test_dataset_mt_fix, batch_size=256, shuffle=False)\n",
    "class FixedMultiTaskLSTMAttention(nn.Module):\n",
    "    def __init__(self, input_dim, hidden_dim=32, num_layers=1, dropout=0.3):\n",
    "        super().__init__()\n",
    "        \n",
    "        self.lstm = nn.LSTM(\n",
    "            input_size=input_dim,\n",
    "            hidden_size=hidden_dim,\n",
    "            num_layers=num_layers,\n",
    "            batch_first=True,\n",
    "            dropout=0.0 if num_layers == 1 else dropout\n",
    "        )\n",
    "        \n",
    "        self.attn = nn.Linear(hidden_dim, 1)\n",
    "        \n",
    "        self.shared = nn.Sequential(\n",
    "            nn.Linear(hidden_dim, 32),\n",
    "            nn.ReLU(),\n",
    "            nn.Dropout(dropout)\n",
    "        )\n",
    "        \n",
    "        self.rv_head = nn.Sequential(\n",
    "            nn.Linear(32, 16),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(16, 1)\n",
    "        )\n",
    "        \n",
    "        self.dsv_head = nn.Sequential(\n",
    "            nn.Linear(32, 16),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(16, 1)\n",
    "        )\n",
    "        \n",
    "        self.score_head = nn.Sequential(\n",
    "            nn.Linear(32, 16),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(16, 1)\n",
    "        )\n",
    "        \n",
    "        self.cls_head = nn.Sequential(\n",
    "            nn.Linear(32, 16),\n",
    "            nn.ReLU(),\n",
    "            nn.Linear(16, 1)\n",
    "        )\n",
    "    \n",
    "    def forward(self, x):\n",
    "        out, _ = self.lstm(x)\n",
    "        attn_weights = torch.softmax(self.attn(out), dim=1)\n",
    "        context = torch.sum(attn_weights * out, dim=1)\n",
    "        z = self.shared(context)\n",
    "        \n",
    "        rv_pred_z = self.rv_head(z).squeeze(-1)\n",
    "        dsv_pred_z = self.dsv_head(z).squeeze(-1)\n",
    "        score_pred_z = self.score_head(z).squeeze(-1)\n",
    "        cls_logit = self.cls_head(z).squeeze(-1)\n",
    "        \n",
    "        return rv_pred_z, dsv_pred_z, score_pred_z, cls_logit\n",
    "def train_fixed_multitask_model(\n",
    "    model,\n",
    "    train_loader,\n",
    "    val_loader,\n",
    "    epochs=30,\n",
    "    lr=5e-4,\n",
    "    w_rv=1.0,\n",
    "    w_dsv=1.0,\n",
    "    w_score=0.2,\n",
    "    w_cls=1.0,\n",
    "    patience=5\n",
    "):\n",
    "    model = model.to(DEVICE)\n",
    "    \n",
    "    optimizer = torch.optim.Adam(model.parameters(), lr=lr)\n",
    "    mse_loss = nn.MSELoss()\n",
    "    bce_loss = nn.BCEWithLogitsLoss()\n",
    "    \n",
    "    best_val_loss = np.inf\n",
    "    best_state = None\n",
    "    wait = 0\n",
    "    \n",
    "    train_losses = []\n",
    "    val_losses = []\n",
    "    \n",
    "    for epoch in range(epochs):\n",
    "        model.train()\n",
    "        running_train_loss = 0.0\n",
    "        \n",
    "        for xb, y_reg_zb, y_reg_rawb, y_clsb in train_loader:\n",
    "            xb = xb.to(DEVICE)\n",
    "            y_reg_zb = y_reg_zb.to(DEVICE)\n",
    "            y_clsb = y_clsb.to(DEVICE)\n",
    "            \n",
    "            optimizer.zero_grad()\n",
    "            \n",
    "            rv_pred_z, dsv_pred_z, score_pred_z, cls_logit = model(xb)\n",
    "            \n",
    "            loss_rv = mse_loss(rv_pred_z, y_reg_zb[:, 0])\n",
    "            loss_dsv = mse_loss(dsv_pred_z, y_reg_zb[:, 1])\n",
    "            loss_score = mse_loss(score_pred_z, y_reg_zb[:, 2])\n",
    "            loss_cls = bce_loss(cls_logit, y_clsb)\n",
    "            \n",
    "            loss = (\n",
    "                w_rv * loss_rv +\n",
    "                w_dsv * loss_dsv +\n",
    "                w_score * loss_score +\n",
    "                w_cls * loss_cls\n",
    "            )\n",
    "            \n",
    "            loss.backward()\n",
    "            optimizer.step()\n",
    "            \n",
    "            running_train_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        epoch_train_loss = running_train_loss / len(train_loader.dataset)\n",
    "        train_losses.append(epoch_train_loss)\n",
    "        \n",
    "        model.eval()\n",
    "        running_val_loss = 0.0\n",
    "        \n",
    "        with torch.no_grad():\n",
    "            for xb, y_reg_zb, y_reg_rawb, y_clsb in val_loader:\n",
    "                xb = xb.to(DEVICE)\n",
    "                y_reg_zb = y_reg_zb.to(DEVICE)\n",
    "                y_clsb = y_clsb.to(DEVICE)\n",
    "                \n",
    "                rv_pred_z, dsv_pred_z, score_pred_z, cls_logit = model(xb)\n",
    "                \n",
    "                loss_rv = mse_loss(rv_pred_z, y_reg_zb[:, 0])\n",
    "                loss_dsv = mse_loss(dsv_pred_z, y_reg_zb[:, 1])\n",
    "                loss_score = mse_loss(score_pred_z, y_reg_zb[:, 2])\n",
    "                loss_cls = bce_loss(cls_logit, y_clsb)\n",
    "                \n",
    "                loss = (\n",
    "                    w_rv * loss_rv +\n",
    "                    w_dsv * loss_dsv +\n",
    "                    w_score * loss_score +\n",
    "                    w_cls * loss_cls\n",
    "                )\n",
    "                \n",
    "                running_val_loss += loss.item() * xb.size(0)\n",
    "        \n",
    "        epoch_val_loss = running_val_loss / len(val_loader.dataset)\n",
    "        val_losses.append(epoch_val_loss)\n",
    "        \n",
    "        print(f\"Epoch {epoch+1:02d} | Train Loss: {epoch_train_loss:.6f} | Val Loss: {epoch_val_loss:.6f}\")\n",
    "        \n",
    "        if epoch_val_loss < best_val_loss:\n",
    "            best_val_loss = epoch_val_loss\n",
    "            best_state = model.state_dict()\n",
    "            wait = 0\n",
    "        else:\n",
    "            wait += 1\n",
    "            if wait >= patience:\n",
    "                print(f\"Early stopping at epoch {epoch+1}\")\n",
    "                break\n",
    "    \n",
    "    model.load_state_dict(best_state)\n",
    "    return model, train_losses, val_losses\n",
    "mt_fix_model = FixedMultiTaskLSTMAttention(\n",
    "    input_dim=len(feature_cols),\n",
    "    hidden_dim=32,\n",
    "    num_layers=1,\n",
    "    dropout=0.3\n",
    ")\n",
    "\n",
    "mt_fix_model, mt_fix_train_losses, mt_fix_val_losses = train_fixed_multitask_model(\n",
    "    mt_fix_model,\n",
    "    train_loader_mt_fix,\n",
    "    val_loader_mt_fix,\n",
    "    epochs=30,\n",
    "    lr=5e-4,\n",
    "    w_rv=1.0,\n",
    "    w_dsv=1.0,\n",
    "    w_score=0.2,\n",
    "    w_cls=1.0,\n",
    "    patience=5\n",
    ")\n",
    "def predict_fixed_multitask(model, loader, target_means, target_stds):\n",
    "    model.eval()\n",
    "    \n",
    "    rv_pred_z, dsv_pred_z, score_pred_z, cls_probs = [], [], [], []\n",
    "    y_reg_raw_true, y_cls_true = [], []\n",
    "    \n",
    "    with torch.no_grad():\n",
    "        for xb, y_reg_zb, y_reg_rawb, y_clsb in loader:\n",
    "            xb = xb.to(DEVICE)\n",
    "            \n",
    "            rv_z, dsv_z, score_z, cls_logit = model(xb)\n",
    "            cls_prob = torch.sigmoid(cls_logit)\n",
    "            \n",
    "            rv_pred_z.extend(rv_z.cpu().numpy())\n",
    "            dsv_pred_z.extend(dsv_z.cpu().numpy())\n",
    "            score_pred_z.extend(score_z.cpu().numpy())\n",
    "            cls_probs.extend(cls_prob.cpu().numpy())\n",
    "            \n",
    "            y_reg_raw_true.extend(y_reg_rawb.numpy())\n",
    "            y_cls_true.extend(y_clsb.numpy())\n",
    "    \n",
    "    rv_pred_z = np.array(rv_pred_z)\n",
    "    dsv_pred_z = np.array(dsv_pred_z)\n",
    "    score_pred_z = np.array(score_pred_z)\n",
    "    \n",
    "    rv_pred = rv_pred_z * target_stds[\"future_rv_5\"] + target_means[\"future_rv_5\"]\n",
    "    dsv_pred = dsv_pred_z * target_stds[\"future_dsv_5\"] + target_means[\"future_dsv_5\"]\n",
    "    score_pred = score_pred_z * target_stds[\"future_score_5\"] + target_means[\"future_score_5\"]\n",
    "    \n",
    "    return {\n",
    "        \"rv_pred\": rv_pred,\n",
    "        \"dsv_pred\": dsv_pred,\n",
    "        \"score_pred\": score_pred,\n",
    "        \"cls_prob\": np.array(cls_probs),\n",
    "        \"y_reg_true\": np.array(y_reg_raw_true),\n",
    "        \"y_cls_true\": np.array(y_cls_true)\n",
    "    }\n",
    "val_mt_fix = predict_fixed_multitask(mt_fix_model, val_loader_mt_fix, target_means, target_stds)\n",
    "test_mt_fix = predict_fixed_multitask(mt_fix_model, test_loader_mt_fix, target_means, target_stds)\n",
    "\n",
    "print(\"Validation: future_rv_5\")\n",
    "regression_metrics(val_mt_fix[\"y_reg_true\"][:, 0], val_mt_fix[\"rv_pred\"], \"Fixed MT-LSTM Validation RV\")\n",
    "\n",
    "print(\"Test: future_rv_5\")\n",
    "regression_metrics(test_mt_fix[\"y_reg_true\"][:, 0], test_mt_fix[\"rv_pred\"], \"Fixed MT-LSTM Test RV\")\n",
    "\n",
    "print(\"Validation: future_dsv_5\")\n",
    "regression_metrics(val_mt_fix[\"y_reg_true\"][:, 1], val_mt_fix[\"dsv_pred\"], \"Fixed MT-LSTM Validation DSV\")\n",
    "\n",
    "print(\"Test: future_dsv_5\")\n",
    "regression_metrics(test_mt_fix[\"y_reg_true\"][:, 1], test_mt_fix[\"dsv_pred\"], \"Fixed MT-LSTM Test DSV\")\n",
    "\n",
    "print(\"Validation: future_score_5\")\n",
    "regression_metrics(val_mt_fix[\"y_reg_true\"][:, 2], val_mt_fix[\"score_pred\"], \"Fixed MT-LSTM Validation Score\")\n",
    "\n",
    "print(\"Test: future_score_5\")\n",
    "regression_metrics(test_mt_fix[\"y_reg_true\"][:, 2], test_mt_fix[\"score_pred\"], \"Fixed MT-LSTM Test Score\")\n",
    "\n",
    "val_cls_fix_pred = (val_mt_fix[\"cls_prob\"] >= 0.5).astype(int)\n",
    "test_cls_fix_pred = (test_mt_fix[\"cls_prob\"] >= 0.5).astype(int)\n",
    "\n",
    "print(\"Validation: quality_label_5\")\n",
    "classification_metrics(val_mt_fix[\"y_cls_true\"], val_cls_fix_pred, val_mt_fix[\"cls_prob\"], \"Fixed MT-LSTM Validation CLS\")\n",
    "\n",
    "print(\"Test: quality_label_5\")\n",
    "classification_metrics(test_mt_fix[\"y_cls_true\"], test_cls_fix_pred, test_mt_fix[\"cls_prob\"], \"Fixed MT-LSTM Test CLS\")\n",
    "plt.figure(figsize=(10, 5))\n",
    "plt.plot(mt_fix_train_losses, label=\"Train Loss\")\n",
    "plt.plot(mt_fix_val_losses, label=\"Validation Loss\")\n",
    "plt.title(\"Fixed Multi-Task LSTM Training Curve\")\n",
    "plt.xlabel(\"Epoch\")\n",
    "plt.ylabel(\"Combined Loss\")\n",
    "plt.legend()\n",
    "plt.show()\n",
    "mt_compare_rows = []\n",
    "\n",
    "mt_compare_rows.append({\n",
    "    \"Model\": \"Old Multi-Task LSTM\",\n",
    "    \"Task\": \"future_rv_5\",\n",
    "    \"RMSE\": np.sqrt(mean_squared_error(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"])),\n",
    "    \"MAE\": mean_absolute_error(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"]),\n",
    "    \"R2\": r2_score(test_mt[\"y_reg_true\"][:, 0], test_mt[\"rv_pred\"])\n",
    "})\n",
    "\n",
    "mt_compare_rows.append({\n",
    "    \"Model\": \"Fixed Multi-Task LSTM\",\n",
    "    \"Task\": \"future_rv_5\",\n",
    "    \"RMSE\": np.sqrt(mean_squared_error(test_mt_fix[\"y_reg_true\"][:, 0], test_mt_fix[\"rv_pred\"])),\n",
    "    \"MAE\": mean_absolute_error(test_mt_fix[\"y_reg_true\"][:, 0], test_mt_fix[\"rv_pred\"]),\n",
    "    \"R2\": r2_score(test_mt_fix[\"y_reg_true\"][:, 0], test_mt_fix[\"rv_pred\"])\n",
    "})\n",
    "\n",
    "pd.DataFrame(mt_compare_rows)\n",
    "cls_compare_rows = []\n",
    "\n",
    "cls_compare_rows.append({\n",
    "    \"Model\": \"Logistic Regression\",\n",
    "    \"Accuracy\": accuracy_score(y_test_cls5, test_pred_logit),\n",
    "    \"Precision\": precision_score(y_test_cls5, test_pred_logit, zero_division=0),\n",
    "    \"Recall\": recall_score(y_test_cls5, test_pred_logit, zero_division=0),\n",
    "    \"F1\": f1_score(y_test_cls5, test_pred_logit, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(y_test_cls5, test_prob_logit)\n",
    "})\n",
    "\n",
    "cls_compare_rows.append({\n",
    "    \"Model\": \"Random Forest\",\n",
    "    \"Accuracy\": accuracy_score(y_test_cls5, test_pred_rf_cls),\n",
    "    \"Precision\": precision_score(y_test_cls5, test_pred_rf_cls, zero_division=0),\n",
    "    \"Recall\": recall_score(y_test_cls5, test_pred_rf_cls, zero_division=0),\n",
    "    \"F1\": f1_score(y_test_cls5, test_pred_rf_cls, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(y_test_cls5, test_prob_rf)\n",
    "})\n",
    "\n",
    "cls_compare_rows.append({\n",
    "    \"Model\": \"Old Multi-Task LSTM\",\n",
    "    \"Accuracy\": accuracy_score(test_mt[\"y_cls_true\"], test_cls_pred),\n",
    "    \"Precision\": precision_score(test_mt[\"y_cls_true\"], test_cls_pred, zero_division=0),\n",
    "    \"Recall\": recall_score(test_mt[\"y_cls_true\"], test_cls_pred, zero_division=0),\n",
    "    \"F1\": f1_score(test_mt[\"y_cls_true\"], test_cls_pred, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(test_mt[\"y_cls_true\"], test_mt[\"cls_prob\"])\n",
    "})\n",
    "\n",
    "cls_compare_rows.append({\n",
    "    \"Model\": \"Fixed Multi-Task LSTM\",\n",
    "    \"Accuracy\": accuracy_score(test_mt_fix[\"y_cls_true\"], test_cls_fix_pred),\n",
    "    \"Precision\": precision_score(test_mt_fix[\"y_cls_true\"], test_cls_fix_pred, zero_division=0),\n",
    "    \"Recall\": recall_score(test_mt_fix[\"y_cls_true\"], test_cls_fix_pred, zero_division=0),\n",
    "    \"F1\": f1_score(test_mt_fix[\"y_cls_true\"], test_cls_fix_pred, zero_division=0),\n",
    "    \"ROC_AUC\": roc_auc_score(test_mt_fix[\"y_cls_true\"], test_mt_fix[\"cls_prob\"])\n",
    "})\n",
    "\n",
    "pd.DataFrame(cls_compare_rows)\n",
    "test_meta_mt_fix = pd.DataFrame(test_dataset_mt_fix.meta, columns=[\"ticker\", \"Date\"])\n",
    "test_meta_mt_fix[\"Date\"] = pd.to_datetime(test_meta_mt_fix[\"Date\"])\n",
    "test_meta_mt_fix[\"actual_rv5\"] = test_mt_fix[\"y_reg_true\"][:, 0]\n",
    "test_meta_mt_fix[\"pred_mt_fix_rv5\"] = test_mt_fix[\"rv_pred\"]\n",
    "\n",
    "plot_mt_fix_df = test_meta_mt_fix[test_meta_mt_fix[\"ticker\"] == \"SPY\"].sort_values(\"Date\").tail(200)\n",
    "\n",
    "plt.figure(figsize=(14, 5))\n",
    "plt.plot(plot_mt_fix_df[\"Date\"], plot_mt_fix_df[\"actual_rv5\"], label=\"Actual\")\n",
    "plt.plot(plot_mt_fix_df[\"Date\"], plot_mt_fix_df[\"pred_mt_fix_rv5\"], label=\"Fixed Multi-Task LSTM\")\n",
    "plt.title(\"SPY: 5-Day Ahead Realized Volatility (Fixed Multi-Task LSTM)\")\n",
    "plt.legend()\n",
    "plt.show()\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python (stockdl)",
   "language": "python",
   "name": "stockdl"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.13"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
